### ISSUE TITLE
plugin is not loading

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/supybot-fedora#11]
supybot Fedora plugin failed to load

```
INFO 2013-09-20T21:20:55 Downloading user data
ERROR 2013-09-20T21:28:19 Failed to load Fedora:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/supybot/plugins/Owner/plugin.py", line 210, in _loadPlugins
    plugin.loadPluginClass(irc, m)
  File "/usr/lib/python2.7/site-packages/supybot/plugin.py", line 86, in loadPluginClass
    cb = module.Class(irc)
  File "/usr/lib/python2.7/site-packages/supybot/utils/python.py", line 98, in __init__
    original__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/supybot/plugins/Fedora/plugin.py", line 114, in __init__
    self._refresh()
  File "/usr/lib/python2.7/site-packages/supybot/plugins/Fedora/plugin.py", line 123, in _refresh
    auth=True)
  File "/usr/lib/python2.7/site-packages/fedora/client/baseclient.py", line 344, in send_request
    auth_params=auth_params, retries=retries)
  File "/usr/lib/python2.7/site-packages/fedora/client/proxyclient.py", line 392, in send_request
    {'url': to_bytes(url), 'err': to_bytes(e)})
ServerError: ServerError(https://admin.fedoraproject.org/accounts/user/list, 200, Error returned from json module while processing https://admin.fedoraproject.org/accounts/user/list: Unterminated string starting at: line 1 column 78302843 (char 78302842))
ERROR 2013-09-20T21:28:19 Exception id: 0xfc976
```

**Comment by ralphbean** [comment]
This is just a temporary error from FAS.  :(  Every now and then it cuts out and falls over.

You have to ask the plugin to reload its data again when this happens with ``.refresh``.
