### ISSUE TITLE
Fix nextmeeting

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/supybot-fedora#19]
It got broken in the last release when the fedocal code got rearranged.

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/supybot/callbacks.py", line 1198, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/supybot/utils/python.py", line 86, in g
    f(self, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/supybot/callbacks.py", line 1184, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/supybot/commands.py", line 974, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/usr/lib/python2.6/site-packages/supybot/plugins/Fedora/plugin.py", line 646, in nextmeeting
    'planet': 'PLN',
  File "/usr/lib/python2.6/site-packages/supybot/plugins/Fedora/plugin.py", line 667, in _future_meetings
    # Now, build another lookup of our various timeframes.
AttributeError: type object 'Fedora' has no attribute '_query_fedocal'
```

**Comment by ralphbean** [comment]
This was fixed.
