### ISSUE TITLE
traceback in members command

### ISSUE THREAD

**Issue by nirik** [fedora-infra/supybot-fedora#94]
INFO 2021-11-11T15:32:23 supybot members called on #fedora-mindshare by "thunderbirdtr!uid500500@fedora/thunderbirdtr".
ERROR 2021-11-11T15:32:23 supybot Spec: [<context for text>]
ERROR 2021-11-11T15:32:23 supybot Received args: []
ERROR 2021-11-11T15:32:23 supybot Extra args: ['name']
ERROR 2021-11-11T15:32:23 supybot Uncaught exception in ['members'].
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fasjson_client/response.py", line 41, in __call__
    call_result = self.operation(**kwargs).response().result
  File "/usr/lib/python3.6/site-packages/bravado/http_future.py", line 239, in response
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/bravado/http_future.py", line 200, in response
    swagger_result = self._get_swagger_result(incoming_response)
  File "/usr/lib/python3.6/site-packages/bravado/http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/bravado/http_future.py", line 303, in _get_swagger_result
    self.request_config.response_callbacks,
  File "/usr/lib/python3.6/site-packages/bravado/http_future.py", line 334, in unmarshal_response
    raise_on_unexpected(incoming_response)
  File "/usr/lib/python3.6/site-packages/bravado/http_future.py", line 408, in raise_on_unexpected
    raise make_http_exception(response=http_response)
bravado.exception.HTTPInternalServerError: 500 INTERNAL SERVER ERROR: {"message": "Internal Server Error"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/supybot/plugins/Fedora/plugin.py", line 861, in members
    members = self.fasjsonclient.list_group_members(groupname=name).result
  File "/usr/lib/python3.6/site-packages/fasjson_client/response.py", line 43, in __call__
    raise APIError.from_bravado_error(e)
fasjson_client.errors.APIError: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/supybot/callbacks.py", line 1552, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/supybot/callbacks.py", line 1518, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/supybot/commands.py", line 1116, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/usr/lib/python3.6/site-packages/supybot/plugins/Fedora/plugin.py", line 868, in members
    self.log.error(e)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1337, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.6/site-packages/supybot/log.py", line 88, in _log
    msg = format(msg, *args)
  File "/usr/lib/python3.6/site-packages/supybot/utils/str.py", line 631, in format
    return _formatRe.sub(sub, s)
TypeError: expected string or bytes-like object
ERROR 2021-11-11T15:32:23 supybot Exception id: 0x44436

**Comment by nirik** [comment]
I did a 'reload Fedora' and then it started working. 

I wonder if something isn't expiring and it needs to reload after a while?

**Comment by nirik** [comment]
This seems to be happening more often now (or people are complaining more often). 

See: https://pagure.io/fedora-infrastructure/issue/11306 for example. 

but there's been many more requests to reload the plugin when it happens. ;(
